#!/usr/bin/env python

import os
Import("env")
Import("env_modules")

os.system('cmake .')
os.system('make gblue_autogen')

env_module = env_modules.Clone()
env_module.Append(
	CPPFLAGS=["-Imodules/bluetooth_module/src", "-Imodules/bluetooth_module/gblue_autogen/include", "-I/usr/include/qt5", "-I/usr/lib64/qt5/mkspecs/linux-g++", "-fPIC"],
	CXXFLAGS=["-std=c++17", "-std=gnu++17", "-DQT_BLUETOOTH_LIB", "-DQT_CORE_LIB", "-DQT_GUI_LIB", "-DQT_NO_DEBUG", "-DQT_WIDGETS_LIB"]
)
# env_module.Append(CPPPATH=["src"])

env_module.add_source_files(env.modules_sources, "src/*.cpp")
env_module.add_source_files(env.modules_sources, "*.cpp")

# -rdynamic
env.Append(LIBPATH=['/usr/lib64'])
env.Append(LIBS=['Qt5Core', 'Qt5Widgets', 'Qt5Gui', 'Qt5Bluetooth'])